export const defaultSiteSections = [
  {
    id: "hero",
    label: "Hero",
    anchor: "#hero",
    enabled: true,
    navVisible: false,
    footerVisible: false,
    eyebrow: "",
    heading: "Quantum manifestation coaching for visionaries ready to lead themselves.",
    description:
      "Hey love, I'm Nehal Patel. I help you manifest with integrity-honoring both the mystical and the practical. Together we create a sustainable, regulated, joyful path to your next level.",
    descriptionSecondary: "",
    primaryCtaLabel: "Explore offerings",
    primaryCtaHref: "#programs",
    secondaryCtaLabel: "Book a discovery call",
    secondaryCtaHref: "#contact",
    supportingEyebrow: "",
    supportingHeading: "",
    supportingDescription: "",
    supportingNote: "",
    formHeading: "",
    formDescription: "",
    formSubmitLabel: "",
    formDisclaimer: "",
    formAction: "",
    featuredOfferingId: "",
  },
  {
    id: "about",
    label: "About",
    anchor: "#about",
    enabled: true,
    navVisible: true,
    footerVisible: true,
    eyebrow: "About the movement",
    heading: "A grounded spiritual practice for real-world transformation.",
    description: "Manifestation work that blends devotion, nervous-system safety, and daily embodiment.",
    descriptionSecondary:
      "Whether you join for high-touch private mentorship, immersive audio coaching, or heart-led community circles, every offering is designed to amplify your energy and make manifestation practical, joyful, and deeply personal.",
    primaryCtaLabel: "",
    primaryCtaHref: "",
    secondaryCtaLabel: "",
    secondaryCtaHref: "",
    supportingEyebrow: "Around the world",
    supportingHeading: "Our users are building new realities globally",
    supportingDescription:
      "High Frequencies 11 supports clients across time zones, cultures, and chapters of life. The work may be personal, but the movement is international.",
    supportingNote:
      "From North America to Europe, the Middle East, Africa, Asia, and Australia, our community keeps expanding through aligned support and word of mouth.",
    formHeading: "",
    formDescription: "",
    formSubmitLabel: "",
    formDisclaimer: "",
    formAction: "",
    featuredOfferingId: "",
  },
  {
    id: "programs",
    label: "Programs",
    anchor: "#programs",
    enabled: true,
    navVisible: true,
    footerVisible: true,
    eyebrow: "Offerings",
    heading: "Choose the support that aligns with your season of growth.",
    description:
      "Every option below is a living portal into your next reality. Select what resonates now and I will follow up with next steps within 24 hours.",
    descriptionSecondary: "",
    primaryCtaLabel: "",
    primaryCtaHref: "",
    secondaryCtaLabel: "",
    secondaryCtaHref: "",
    supportingEyebrow: "",
    supportingHeading: "",
    supportingDescription: "",
    supportingNote: "",
    formHeading: "",
    formDescription: "",
    formSubmitLabel: "",
    formDisclaimer: "",
    formAction: "",
    featuredOfferingId: "",
  },
  {
    id: "services",
    label: "Services",
    anchor: "#services",
    enabled: true,
    navVisible: true,
    footerVisible: true,
    eyebrow: "The experience",
    heading: "What makes High Frequencies 11 different.",
    description:
      "These pillars define every session, program, and resource we create. You will be seen, supported, and stretched into your next evolution.",
    descriptionSecondary: "",
    primaryCtaLabel: "",
    primaryCtaHref: "",
    secondaryCtaLabel: "",
    secondaryCtaHref: "",
    supportingEyebrow: "",
    supportingHeading: "",
    supportingDescription: "",
    supportingNote: "",
    formHeading: "",
    formDescription: "",
    formSubmitLabel: "",
    formDisclaimer: "",
    formAction: "",
    featuredOfferingId: "",
  },
  {
    id: "testimonials",
    label: "Testimonials",
    anchor: "#testimonials",
    enabled: true,
    navVisible: true,
    footerVisible: true,
    eyebrow: "Testimonials",
    heading: "Words from the High Frequencies 11 collective.",
    description: "Real people. Real timelines collapsing. Real lives transforming.",
    descriptionSecondary: "",
    primaryCtaLabel: "",
    primaryCtaHref: "",
    secondaryCtaLabel: "",
    secondaryCtaHref: "",
    supportingEyebrow: "",
    supportingHeading: "",
    supportingDescription: "",
    supportingNote: "",
    formHeading: "",
    formDescription: "",
    formSubmitLabel: "",
    formDisclaimer: "",
    formAction: "",
    featuredOfferingId: "",
  },
  {
    id: "resources",
    label: "Resources",
    anchor: "#resources",
    enabled: true,
    navVisible: false,
    footerVisible: false,
    eyebrow: "Resources",
    heading: "Continue the frequency work between sessions.",
    description: "A curated library of free and paid resources to support your practice.",
    descriptionSecondary: "",
    primaryCtaLabel: "",
    primaryCtaHref: "",
    secondaryCtaLabel: "",
    secondaryCtaHref: "",
    supportingEyebrow: "",
    supportingHeading: "",
    supportingDescription: "",
    supportingNote: "",
    formHeading: "",
    formDescription: "",
    formSubmitLabel: "",
    formDisclaimer: "",
    formAction: "",
    featuredOfferingId: "",
  },
  {
    id: "coaching",
    label: "Coaching CTA",
    anchor: "#coaching",
    enabled: true,
    navVisible: false,
    footerVisible: false,
    eyebrow: "Click down below for personalised one-on-one coaching",
    heading: "Personalised Coaching with me for 30 days",
    description: "Private high-touch mentorship to collapse timelines and support your full embodiment.",
    descriptionSecondary: "",
    primaryCtaLabel: "Become a new you here",
    primaryCtaHref: "",
    secondaryCtaLabel: "",
    secondaryCtaHref: "",
    supportingEyebrow: "Investment",
    supportingHeading: "",
    supportingDescription: "",
    supportingNote: "30 days • private Voxer/email support • personalised meditations",
    formHeading: "",
    formDescription: "",
    formSubmitLabel: "",
    formDisclaimer: "",
    formAction: "",
    featuredOfferingId: "become-a-new-you",
  },
  {
    id: "contact",
    label: "Contact",
    anchor: "#contact",
    enabled: true,
    navVisible: true,
    footerVisible: true,
    eyebrow: "Connect",
    heading: "Ready to raise your frequency?",
    description:
      "Tell me about the reality you are stepping into and how you desire to be supported. I respond to all inquiries within 48 hours Monday through Friday.",
    descriptionSecondary: "",
    primaryCtaLabel: "",
    primaryCtaHref: "",
    secondaryCtaLabel: "",
    secondaryCtaHref: "",
    supportingEyebrow: "",
    supportingHeading: "",
    supportingDescription: "",
    supportingNote: "",
    formHeading: "Share your intentions",
    formDescription:
      "This form lands directly in my inbox. Share your story, desires, and what kind of support you are calling in.",
    formSubmitLabel: "Send message",
    formDisclaimer:
      "By submitting this form you agree to receive occasional updates about High Frequencies 11 offerings. You can opt out at any time.",
    formAction: "",
    featuredOfferingId: "",
  },
  {
    id: "newsletter",
    label: "Newsletter",
    anchor: "#newsletter",
    enabled: true,
    navVisible: false,
    footerVisible: true,
    eyebrow: "The Frequency Drop",
    heading: "Stay plugged into the vortex.",
    description: "Receive monthly energy reports, journal prompts, and VIP offers.",
    descriptionSecondary: "",
    primaryCtaLabel: "Join now",
    primaryCtaHref: "",
    secondaryCtaLabel: "",
    secondaryCtaHref: "",
    supportingEyebrow: "",
    supportingHeading: "",
    supportingDescription: "",
    supportingNote: "No spam. Just potent reminders.",
    formHeading: "",
    formDescription: "",
    formSubmitLabel: "",
    formDisclaimer: "",
    formAction: "https://formspree.io/f/xovqwaaw",
    featuredOfferingId: "",
  },
];

export const defaultSiteSectionItems = [
  { key: "hero-proof-strategy", sectionKey: "hero", itemType: "card", title: "Aligned Strategy", description: "Energetic calibrations paired with tangible daily actions.", label: "", href: "", icon: "", imageUrl: "", imageAlt: "", sortOrder: 0, enabled: true },
  { key: "hero-proof-discipline", sectionKey: "hero", itemType: "card", title: "Sacred Discipline", description: "Rituals that keep you grounded while your manifestations unfold.", label: "", href: "", icon: "", imageUrl: "", imageAlt: "", sortOrder: 1, enabled: true },
  { key: "hero-proof-support", sectionKey: "hero", itemType: "card", title: "Devoted Support", description: "A coach, cheerleader, and mirror as you lead your divine mission.", label: "", href: "", icon: "", imageUrl: "", imageAlt: "", sortOrder: 2, enabled: true },
  { key: "about-metric-clients", sectionKey: "about", itemType: "metric", title: "1,000+", description: "souls supported through sessions, workshops, and digital communities", label: "", href: "", icon: "", imageUrl: "", imageAlt: "", sortOrder: 0, enabled: true },
  { key: "about-metric-years", sectionKey: "about", itemType: "metric", title: "8+ years", description: "of practical manifestation and mindset coaching experience", label: "", href: "", icon: "", imageUrl: "", imageAlt: "", sortOrder: 1, enabled: true },
  { key: "about-metric-global", sectionKey: "about", itemType: "metric", title: "Global", description: "clients from 15 countries united by the High Frequencies 11 movement", label: "", href: "", icon: "", imageUrl: "", imageAlt: "", sortOrder: 2, enabled: true },
  { key: "services-practice", sectionKey: "services", itemType: "card", title: "Somatic & Energetic Practices", description: "Breathwork, tapping, and body-led rituals that keep your nervous system anchored while you quantum leap.", label: "", href: "", icon: "sparkles", imageUrl: "", imageAlt: "", sortOrder: 0, enabled: true },
  { key: "services-frameworks", sectionKey: "services", itemType: "card", title: "Manifestation Frameworks", description: "Signature High Frequencies 11 methods that blend neuroscience with spiritual teachings for tangible shifts.", label: "", href: "", icon: "layers", imageUrl: "", imageAlt: "", sortOrder: 1, enabled: true },
  { key: "services-resources", sectionKey: "services", itemType: "card", title: "Lifetime-Ready Resources", description: "Journals, guided meditations, and replay libraries you can return to whenever you need a frequency boost.", label: "", href: "", icon: "library", imageUrl: "", imageAlt: "", sortOrder: 2, enabled: true },
  { key: "services-community", sectionKey: "services", itemType: "card", title: "Community & Accountability", description: "Monthly circles, private Voxer channels, and global members who are walking the same path by your side.", label: "", href: "", icon: "users", imageUrl: "", imageAlt: "", sortOrder: 3, enabled: true },
  { key: "resources-podcast", sectionKey: "resources", itemType: "link", title: "Podcast: High Frequencies 11", description: "Weekly activations, channelled messages, and conversations about manifestation, mindset, and miracles.", label: "Listen on Spotify", href: "https://open.spotify.com/show/02zFg2ejkXs1XHBo6teu5n", icon: "", imageUrl: "", imageAlt: "", sortOrder: 0, enabled: true },
  { key: "resources-youtube", sectionKey: "resources", itemType: "link", title: "YouTube: @nehalpatelishere", description: "Binge long-form trainings, rituals, and intimate vlogs that make manifestation feel like your daily rhythm.", label: "Subscribe on YouTube", href: "https://www.youtube.com/@nehalpatelishere", icon: "", imageUrl: "", imageAlt: "", sortOrder: 1, enabled: true },
  { key: "resources-amazon", sectionKey: "resources", itemType: "link", title: "Amazon Storefront", description: "Shop the exact books, candles, and ritual tools I use to stay anchored in a high frequency every day.", label: "View the list", href: "https://www.amazon.ca/shop/bookescape_?ref_=cm_sw_r_cp_mwn_aipsfshop_aipsfbookescape__PBB131SY1HEHXB4D7YG2_1&language=en_US", icon: "", imageUrl: "", imageAlt: "", sortOrder: 2, enabled: true },
  { key: "resources-newsletter", sectionKey: "resources", itemType: "link", title: "Newsletter & Free Gifts", description: "Receive monthly energy forecasts, journal prompts, and pop-up offers that keep you plugged into the vortex.", label: "Join the list", href: "#newsletter", icon: "", imageUrl: "", imageAlt: "", sortOrder: 3, enabled: true },
  { key: "coaching-benefit-1", sectionKey: "coaching", itemType: "benefit", title: "Personalised Coaching with me for 30 days", description: "", label: "", href: "", icon: "", imageUrl: "", imageAlt: "", sortOrder: 0, enabled: true },
  { key: "coaching-benefit-2", sectionKey: "coaching", itemType: "benefit", title: "5 calls with me", description: "", label: "", href: "", icon: "", imageUrl: "", imageAlt: "", sortOrder: 1, enabled: true },
  { key: "coaching-benefit-3", sectionKey: "coaching", itemType: "benefit", title: "Unlimited emails or DMs", description: "", label: "", href: "", icon: "", imageUrl: "", imageAlt: "", sortOrder: 2, enabled: true },
  { key: "coaching-benefit-4", sectionKey: "coaching", itemType: "benefit", title: "4 personalized meditations/ rampages", description: "", label: "", href: "", icon: "", imageUrl: "", imageAlt: "", sortOrder: 3, enabled: true },
  { key: "coaching-benefit-5", sectionKey: "coaching", itemType: "benefit", title: "Support for self-concept, mastery, luck, beauty, money, love, and dissolving every block", description: "", label: "", href: "", icon: "", imageUrl: "", imageAlt: "", sortOrder: 4, enabled: true },
  { key: "coaching-benefit-6", sectionKey: "coaching", itemType: "benefit", title: "Manifestation techniques tailored to you including portal visualisations, EFT, and parts work", description: "", label: "", href: "", icon: "", imageUrl: "", imageAlt: "", sortOrder: 5, enabled: true },
  { key: "coaching-benefit-7", sectionKey: "coaching", itemType: "benefit", title: "Daily Affirmations", description: "", label: "", href: "", icon: "", imageUrl: "", imageAlt: "", sortOrder: 6, enabled: true },
  { key: "coaching-benefit-8", sectionKey: "coaching", itemType: "benefit", title: "Guided meditations", description: "", label: "", href: "", icon: "", imageUrl: "", imageAlt: "", sortOrder: 7, enabled: true },
  { key: "coaching-benefit-9", sectionKey: "coaching", itemType: "benefit", title: "30 days of consistent energetic accountability", description: "", label: "", href: "", icon: "", imageUrl: "", imageAlt: "", sortOrder: 8, enabled: true },
];

export const defaultSiteLinks = [
  { key: "contact-email", groupKey: "contact", label: "Email", value: "highfrequencies11@gmail.com", href: "mailto:highfrequencies11@gmail.com", icon: "mail", sortOrder: 0, enabled: true },
  { key: "contact-instagram", groupKey: "contact", label: "Instagram", value: "@highfrequencies11", href: "https://www.instagram.com/highfrequencies11/", icon: "instagram", sortOrder: 1, enabled: true },
  { key: "contact-youtube", groupKey: "contact", label: "YouTube", value: "@nehalpatelishere", href: "https://www.youtube.com/@nehalpatelishere", icon: "youtube", sortOrder: 2, enabled: true },
  { key: "footer-offerings-programs", groupKey: "footer_offerings", label: "Programs", value: "", href: "#programs", icon: "", sortOrder: 0, enabled: true },
  { key: "footer-offerings-services", groupKey: "footer_offerings", label: "Services", value: "", href: "#services", icon: "", sortOrder: 1, enabled: true },
  { key: "footer-offerings-coaching", groupKey: "footer_offerings", label: "1:1 Coaching", value: "", href: "#coaching", icon: "", sortOrder: 2, enabled: true },
  { key: "footer-offerings-resources", groupKey: "footer_offerings", label: "Resources", value: "", href: "#resources", icon: "", sortOrder: 3, enabled: true },
  { key: "footer-offerings-testimonials", groupKey: "footer_offerings", label: "Testimonials", value: "", href: "#testimonials", icon: "", sortOrder: 4, enabled: true },
  { key: "footer-resources-instagram", groupKey: "footer_resources", label: "Instagram", value: "", href: "https://www.instagram.com/highfrequencies11/", icon: "instagram", sortOrder: 0, enabled: true },
  { key: "footer-resources-youtube", groupKey: "footer_resources", label: "YouTube", value: "", href: "https://www.youtube.com/@nehalpatelishere", icon: "youtube", sortOrder: 1, enabled: true },
  { key: "footer-resources-podcast", groupKey: "footer_resources", label: "Podcast", value: "", href: "https://open.spotify.com/show/02zFg2ejkXs1XHBo6teu5n", icon: "music", sortOrder: 2, enabled: true },
  { key: "footer-resources-amazon", groupKey: "footer_resources", label: "Amazon Store", value: "", href: "https://www.amazon.ca/shop/bookescape_?ref_=cm_sw_r_cp_mwn_aipsfshop_aipsfbookescape__PBB131SY1HEHXB4D7YG2_1&language=en_US", icon: "shopping-bag", sortOrder: 3, enabled: true },
  { key: "footer-support-contact", groupKey: "footer_support", label: "Contact", value: "", href: "#contact", icon: "", sortOrder: 0, enabled: true },
  { key: "footer-support-newsletter", groupKey: "footer_support", label: "Newsletter", value: "", href: "#newsletter", icon: "", sortOrder: 1, enabled: true },
  { key: "footer-support-call", groupKey: "footer_support", label: "Book a Call", value: "", href: "#contact", icon: "", sortOrder: 2, enabled: true },
  { key: "footer-support-shop", groupKey: "footer_support", label: "Visit Shop", value: "", href: "/#programs", icon: "", sortOrder: 3, enabled: true },
  { key: "footer-social-instagram", groupKey: "footer_social", label: "Instagram", value: "", href: "https://www.instagram.com/highfrequencies11/", icon: "instagram", sortOrder: 0, enabled: true },
  { key: "footer-social-youtube", groupKey: "footer_social", label: "YouTube", value: "", href: "https://www.youtube.com/@nehalpatelishere", icon: "youtube", sortOrder: 1, enabled: true },
  { key: "footer-social-podcast", groupKey: "footer_social", label: "Podcast", value: "", href: "https://open.spotify.com/show/02zFg2ejkXs1XHBo6teu5n", icon: "music", sortOrder: 2, enabled: true },
  { key: "footer-social-email", groupKey: "footer_social", label: "Email", value: "", href: "mailto:highfrequencies11@gmail.com", icon: "mail", sortOrder: 3, enabled: true },
];

export const defaultSiteSettings = {
  brand: {
    navTitle: "HF11",
    fullTitle: "High Frequencies 11",
    footerTagline:
      "Manifestation mentorship, somatic practices, and community support for leaders building miraculous lives.",
    shopLabel: "Visit shop",
    shopHref: "/#programs",
    supportEmail: "highfrequencies11@gmail.com",
  },
  theme: {
    primary: "#06b6d4",
    primaryLight: "#67e8f9",
    secondary: "#8b5cf6",
    accent: "#ec4899",
    dark: "#0f172a",
  },
  profile: {
    imageUrl: "",
    imageAlt: "Nehal Patel portrait",
    roleLabel: "Manifestation Coach",
  },
  footer: {
    introEyebrow: "High Frequencies 11",
    introHeading: "A devotional storefront for manifestation, ritual, and private transformation.",
    statusLabel: "All frequencies aligned",
    termsLabel: "Terms of Service",
    termsHref: "#contact",
    privacyLabel: "Privacy Policy",
    privacyHref: "#contact",
  },
  faqs: [
    { question: "What is the purpose of this website?", answer: "This website serves as a portal to explore and purchase specialized offerings delivered directly to you. Our focus is on providing high-quality digital content and experiences." },
    { question: "How do I contact support?", answer: "You can reach out to our support team any time via the Contact page or by replying directly to any of your confirmation emails." },
    { question: "How do I find the best products?", answer: "Browse our categories on the main shop page. Each offering details exactly what you'll receive so you can align it with your current goals." },
    { question: "Can I return a product?", answer: "Digital products and services are generally non-refundable once delivered, as they cannot be 'returned'. However, if you experience an issue, please contact support." },
    { question: "Do you offer international shipping?", answer: "All of our offerings are digital deliverables or virtual sessions, meaning we gladly support clients anywhere in the world without shipping constraints." },
    { question: "How can I track my order?", answer: "You will receive an email confirmation with your order details and direct links for any digital downloads immediately after purchase." },
  ],
  sections: defaultSiteSections,
  sectionItems: defaultSiteSectionItems,
  links: defaultSiteLinks,
};

const normalizeString = (value, fallback = "") => {
  const next = typeof value === "string" ? value.trim() : "";
  return next || fallback;
};

const normalizeSectionRow = (row = {}, fallback) => ({
  id: fallback.id,
  label: normalizeString(row.label, fallback.label),
  anchor: normalizeString(row.anchor, fallback.anchor),
  enabled: row.is_enabled !== false,
  navVisible: typeof row.show_in_nav === "boolean" ? row.show_in_nav : fallback.navVisible,
  footerVisible: typeof row.show_in_footer === "boolean" ? row.show_in_footer : fallback.footerVisible,
  eyebrow: normalizeString(row.eyebrow, fallback.eyebrow),
  heading: normalizeString(row.heading, fallback.heading),
  description: normalizeString(row.description, fallback.description),
  descriptionSecondary: normalizeString(row.description_secondary, fallback.descriptionSecondary),
  primaryCtaLabel: normalizeString(row.primary_cta_label, fallback.primaryCtaLabel),
  primaryCtaHref: normalizeString(row.primary_cta_href, fallback.primaryCtaHref),
  secondaryCtaLabel: normalizeString(row.secondary_cta_label, fallback.secondaryCtaLabel),
  secondaryCtaHref: normalizeString(row.secondary_cta_href, fallback.secondaryCtaHref),
  supportingEyebrow: normalizeString(row.supporting_eyebrow, fallback.supportingEyebrow),
  supportingHeading: normalizeString(row.supporting_heading, fallback.supportingHeading),
  supportingDescription: normalizeString(row.supporting_description, fallback.supportingDescription),
  supportingNote: normalizeString(row.supporting_note, fallback.supportingNote),
  formHeading: normalizeString(row.form_heading, fallback.formHeading),
  formDescription: normalizeString(row.form_description, fallback.formDescription),
  formSubmitLabel: normalizeString(row.form_submit_label, fallback.formSubmitLabel),
  formDisclaimer: normalizeString(row.form_disclaimer, fallback.formDisclaimer),
  formAction: normalizeString(row.form_action, fallback.formAction),
  featuredOfferingId: normalizeString(row.featured_offering_id, fallback.featuredOfferingId),
  sortOrder: Number(row.sort_order ?? 0),
});

const normalizeSectionItemRow = (row = {}, fallback = {}) => ({
  key: row.key || fallback.key || `item-${Date.now()}`,
  sectionKey: row.section_key || fallback.sectionKey || "",
  itemType: normalizeString(row.item_type, fallback.itemType || "card"),
  title: normalizeString(row.title, fallback.title || ""),
  description: normalizeString(row.description, fallback.description || ""),
  label: normalizeString(row.label, fallback.label || ""),
  href: normalizeString(row.href, fallback.href || ""),
  icon: normalizeString(row.icon, fallback.icon || ""),
  imageUrl: normalizeString(row.image_url, fallback.imageUrl || ""),
  imageAlt: normalizeString(row.image_alt, fallback.imageAlt || ""),
  sortOrder: Number(row.sort_order ?? fallback.sortOrder ?? 0),
  enabled: row.is_enabled !== false,
});

const normalizeLinkRow = (row = {}, fallback = {}) => ({
  key: row.key || fallback.key || `link-${Date.now()}`,
  groupKey: normalizeString(row.group_key, fallback.groupKey || ""),
  label: normalizeString(row.label, fallback.label || ""),
  value: normalizeString(row.value, fallback.value || ""),
  href: normalizeString(row.href, fallback.href || ""),
  icon: normalizeString(row.icon, fallback.icon || ""),
  sortOrder: Number(row.sort_order ?? fallback.sortOrder ?? 0),
  enabled: row.is_enabled !== false,
});

export const normalizeSiteSettingsFromRows = ({ global = {}, sections = [], sectionItems = [], links = [] } = {}) => {
  const sectionsById = new Map((sections || []).map((section) => [section.key, section]));
  const sectionItemsByKey = new Map((sectionItems || []).map((item) => [item.key, item]));
  const linksByKey = new Map((links || []).map((link) => [link.key, link]));

  const normalizedSections = defaultSiteSections
    .map((fallback) => normalizeSectionRow(sectionsById.get(fallback.id), fallback))
    .sort((a, b) => Number(a.sortOrder || 0) - Number(b.sortOrder || 0));

  const normalizedItems = [
    ...defaultSiteSectionItems.map((fallback) => normalizeSectionItemRow(sectionItemsByKey.get(fallback.key), fallback)),
    ...(sectionItems || [])
      .filter((item) => !defaultSiteSectionItems.some((fallback) => fallback.key === item.key))
      .map((item) => normalizeSectionItemRow(item)),
  ].sort((a, b) => Number(a.sortOrder || 0) - Number(b.sortOrder || 0));

  const normalizedLinks = [
    ...defaultSiteLinks.map((fallback) => normalizeLinkRow(linksByKey.get(fallback.key), fallback)),
    ...(links || [])
      .filter((link) => !defaultSiteLinks.some((fallback) => fallback.key === link.key))
      .map((link) => normalizeLinkRow(link)),
  ].sort((a, b) => Number(a.sortOrder || 0) - Number(b.sortOrder || 0));

  return {
    brand: {
      navTitle: normalizeString(global.brand_nav_title, defaultSiteSettings.brand.navTitle),
      fullTitle: normalizeString(global.brand_full_title, defaultSiteSettings.brand.fullTitle),
      footerTagline: normalizeString(global.brand_footer_tagline, defaultSiteSettings.brand.footerTagline),
      shopLabel: normalizeString(global.brand_shop_label, defaultSiteSettings.brand.shopLabel),
      shopHref: normalizeString(global.brand_shop_href, defaultSiteSettings.brand.shopHref),
      supportEmail: normalizeString(global.brand_support_email, defaultSiteSettings.brand.supportEmail),
    },
    theme: {
      primary: normalizeString(global.theme_primary, defaultSiteSettings.theme.primary),
      primaryLight: normalizeString(global.theme_primary_light, defaultSiteSettings.theme.primaryLight),
      secondary: normalizeString(global.theme_secondary, defaultSiteSettings.theme.secondary),
      accent: normalizeString(global.theme_accent, defaultSiteSettings.theme.accent),
      dark: normalizeString(global.theme_dark, defaultSiteSettings.theme.dark),
    },
    profile: {
      imageUrl: normalizeString(global.profile_image_url, defaultSiteSettings.profile.imageUrl),
      imageAlt: normalizeString(global.profile_image_alt, defaultSiteSettings.profile.imageAlt),
      roleLabel: normalizeString(global.profile_role_label, defaultSiteSettings.profile.roleLabel),
    },
    footer: {
      introEyebrow: normalizeString(global.footer_intro_eyebrow, defaultSiteSettings.footer.introEyebrow),
      introHeading: normalizeString(global.footer_intro_heading, defaultSiteSettings.footer.introHeading),
      statusLabel: normalizeString(global.footer_status_label, defaultSiteSettings.footer.statusLabel),
      termsLabel: normalizeString(global.footer_terms_label, defaultSiteSettings.footer.termsLabel),
      termsHref: normalizeString(global.footer_terms_href, defaultSiteSettings.footer.termsHref),
      privacyLabel: normalizeString(global.footer_privacy_label, defaultSiteSettings.footer.privacyLabel),
      privacyHref: normalizeString(global.footer_privacy_href, defaultSiteSettings.footer.privacyHref),
    },
    faqs: Array.isArray(global.faqs) ? global.faqs : defaultSiteSettings.faqs,
    sections: normalizedSections,
    sectionItems: normalizedItems,
    links: normalizedLinks,
  };
};

export const siteThemeCssVariables = (theme = defaultSiteSettings.theme) => ({
  "--site-brand-primary": theme.primary,
  "--site-brand-primary-light": theme.primaryLight,
  "--site-brand-secondary": theme.secondary,
  "--site-brand-accent": theme.accent,
  "--site-brand-dark": theme.dark,
});
